---
- hosts: master
  become: yes
  vars_files:
    - vars.yml

  tasks:
    - name: Install kubectl
      apt:
        name: kubectl=1.20.0-00
        state: present
        force: yes

    - name: Reset the cluster
      shell: kubeadm reset -f >> cluster_reset.txt

    - name: Initialize the cluster
      shell: kubeadm init --apiserver-advertise-address={{ kubernetes_apiserver_advertise_address }} --pod-network-cidr={{ kubernetes_pod_network_cidr }} >> cluster_initialized.txt

    - name: create .kube directory
      become: yes
      become_user: vagrant
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: Copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/vagrant/.kube/config
        remote_src: yes
        owner: vagrant

    - name: Install Pod network
      become: yes
      become_user: vagrant
      shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')" >> pod_network_setup.txt