apiVersion: v1
kind: Pod
metadata:
  name: echo-app-pod
  labels:
    name: echo-app
spec:
  containers:
  - name: echo-container
    image: busybox:1.28
    command: ['sh', '-c', 'echo This is the echo app && sleep 3600']
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
